plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.furkankayam'
version = 'v.0.1'
description = 'Spring Boot Strategy Pattern Demo'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

ext {
    springdocVersion = '2.8.0'
}

dependencies {
    // --- Core ---
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // --- Lombok ---
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // --- Development Tools ---
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // --- Swagger / OpenAPI ---
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

    // --- Test ---
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}